spring.application.name=java-spring-boot-greeting-service
spring.docker.compose.enabled=false
server.port=8082
logging.level.com.example=debug
management.observations.annotations.enabled=true

management.tracing.sampling.probability=1.0
management.opentelemetry.tracing.export.otlp.endpoint=https://app.trace0hq.com/api/v1/traces
management.otlp.metrics.export.url=https://app.trace0hq.com/api/v1/metrics
management.opentelemetry.logging.export.otlp.endpoint=https://app.trace0hq.com/api/v1/logs
management.opentelemetry.tracing.export.otlp.headers.X-API-KEY=YOUR_TRACE0_ENV_API_KEY
management.otlp.metrics.export.headers.X-API-KEY=YOUR_TRACE0_ENV_API_KEY
management.opentelemetry.logging.export.otlp.headers.X-API-KEY=YOUR_TRACE0_ENV_API_KEY
management.otlp.metrics.export.step=10s
